-- waymark2 migration: generated from the declared registry.
-- Review before applying; lines marked for review need a human.

CREATE OR REPLACE FUNCTION waymark2_ts(value text)
RETURNS timestamptz
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
RETURN value::timestamptz;

CREATE TABLE grocery_lists (
	id VARCHAR(64) NOT NULL, 
	state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	plan_id TEXT GENERATED ALWAYS AS ((data->>'plan_id')) STORED, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_grocery_lists_plan_id ON grocery_lists (plan_id);

CREATE INDEX ix_grocery_lists_state ON grocery_lists (state);

CREATE TABLE jobs (
	id VARCHAR(64) NOT NULL, 
	state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_jobs_state ON jobs (state);

CREATE TABLE meals (
	id VARCHAR(64) NOT NULL, 
	state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	name TEXT GENERATED ALWAYS AS ((data->>'name')) STORED, 
	theme TEXT GENERATED ALWAYS AS ((data->>'theme')) STORED, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_meals_name ON meals (name);

CREATE INDEX ix_meals_state ON meals (state);

CREATE INDEX ix_meals_theme ON meals (theme);

CREATE TABLE plans (
	id VARCHAR(64) NOT NULL, 
	state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	start_date TEXT GENERATED ALWAYS AS ((data->>'start_date')) STORED, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_plans_start_date ON plans (start_date);

CREATE INDEX ix_plans_state ON plans (state);

CREATE TABLE prep_tasks (
	id VARCHAR(64) NOT NULL, 
	state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	due_at TIMESTAMP WITH TIME ZONE GENERATED ALWAYS AS (waymark2_ts(data->>'due_at')) STORED, 
	plan_id TEXT GENERATED ALWAYS AS ((data->>'plan_id')) STORED, 
	task_type TEXT GENERATED ALWAYS AS ((data->>'task_type')) STORED, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_prep_tasks_due_at ON prep_tasks (due_at);

CREATE INDEX ix_prep_tasks_plan_id ON prep_tasks (plan_id);

CREATE INDEX ix_prep_tasks_state ON prep_tasks (state);

CREATE INDEX ix_prep_tasks_task_type ON prep_tasks (task_type);

CREATE TABLE rotations (
	id VARCHAR(64) NOT NULL, 
	state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	data JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_rotations_state ON rotations (state);

CREATE TABLE waymark2_drafts (
	kind VARCHAR(64) NOT NULL, 
	resource_id VARCHAR(64) NOT NULL, 
	action VARCHAR(128) NOT NULL, 
	part_key VARCHAR(128) NOT NULL, 
	audience VARCHAR(128) NOT NULL, 
	values JSONB NOT NULL, 
	revs JSONB NOT NULL, 
	authors JSONB NOT NULL, 
	base_version INTEGER NOT NULL, 
	saved_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (kind, resource_id, action, part_key, audience)
);

CREATE TABLE waymark2_idempotency (
	key VARCHAR(256) NOT NULL, 
	kind VARCHAR(64) NOT NULL, 
	action VARCHAR(128) NOT NULL, 
	body_digest VARCHAR(64) NOT NULL, 
	status INTEGER NOT NULL, 
	response_body BYTEA NOT NULL, 
	media_type VARCHAR(128) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (key)
);

CREATE TABLE waymark2_transitions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	kind VARCHAR(64) NOT NULL, 
	resource_id VARCHAR(64) NOT NULL, 
	action VARCHAR(128) NOT NULL, 
	from_state VARCHAR(64) NOT NULL, 
	to_state VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	actor_type VARCHAR(16) NOT NULL, 
	actor_id VARCHAR(128) NOT NULL, 
	actor_display VARCHAR(256) NOT NULL, 
	input_digest VARCHAR(64) NOT NULL, 
	correlation_id VARCHAR(64), 
	summary TEXT NOT NULL, 
	at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_waymark2_transitions_resource ON waymark2_transitions (kind, resource_id, id);
